# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975d45c81c512ea4257b8b4d89bc3474f6d6a2c673b3750789fdee4d95eaf96b1dc35fa895c4dd0272a8a6f94cd85a716a85005566b41a611bea13f7c05cd83d

test:
  secret_key_base: e99c33a9e195e06f251a223093a60f087524e39c70d67cd239955367776fa505d2dbcceb69b6f1023d14e7d7d17cab68b70f1f0e6af83c209a45c8a44aebbc45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
